include:
  - project: 'dev/prisme/syspo/indus/syspo-shared-ci'
    ref: master
    file: "/common.yml"

stages:
  - install
  - build
  - docker
  - deploy

install:
  stage: install
  extends: .install:npm

package:
  stage: build
  extends: .npm
  script:
    - npm run build
    - >
      export VERSION=$(grep -o '"version": *"[^"]*"' package.json | awk -F'"' '{print $4}')
    - echo "VERSION=${VERSION}" >> build.env
    - echo "VERSION=${VERSION}"
    - echo "SYSPO_DOCKER_VERSION=${VERSION}" >> build.env
  retry: 2
  artifacts:
    expire_in: 3 hour
    paths:
      - dist/
    reports:
      dotenv: build.env

docker:build:release:
  extends: .docker:build:release
  stage: docker
